use angstrom_types::contract_payloads::angstrom::AngstromBundle;
use base64::Engine;
use matching_engine::book::OrderBook;
use testing_tools::type_generator::consensus::{pool::PoolBuilder, proposal::ProposalBuilder};

const BOOK: &str = "eyJpZCI6IjB4YzczNmEyZTczMDU0N2ZlMWE0MWNmNjg2NWNhY2FkMjFlMzY5YjllNDIzMDYxMDUwMjNhOTBmMzVmNDU3NjkwMSIsImFtbSI6bnVsbCwiYmlkcyI6W3sib3JkZXIiOnsiS2lsbE9yRmlsbCI6eyJFeGFjdCI6eyJyZWZfaWQiOjAsImV4YWN0X2luIjpmYWxzZSwiYW1vdW50IjoxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwLCJtYXhfZXh0cmFfZmVlX2Fzc2V0MCI6MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCwibWluX3ByaWNlIjoiMHg1NTg3NDlkYjc3ZjcwMDI5Yzc3NTA2ODIzZDIyYmQwMDAwMDAwMDAwMDAwIiwidXNlX2ludGVybmFsIjpmYWxzZSwiYXNzZXRfaW4iOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAiLCJhc3NldF9vdXQiOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEiLCJyZWNpcGllbnQiOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJob29rX2RhdGEiOiIweCIsInZhbGlkX2Zvcl9ibG9jayI6MCwibWV0YSI6eyJpc0VjZHNhIjpmYWxzZSwiZnJvbSI6IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInNpZ25hdHVyZSI6IjB4In19fX0sInByaW9yaXR5X2RhdGEiOnsicHJpY2UiOiIweDFmNCIsInZvbHVtZSI6MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCwiZ2FzIjoiMHgwIiwiZ2FzX3VuaXRzIjowfSwiaW52YWxpZGF0ZXMiOltdLCJwb29sX2lkIjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwiaXNfY3VycmVudGx5X3ZhbGlkIjp0cnVlLCJpc19iaWQiOnRydWUsImlzX3ZhbGlkIjp0cnVlLCJ2YWxpZF9ibG9jayI6MCwib3JkZXJfaWQiOnsiYWRkcmVzcyI6IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInBvb2xfaWQiOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJoYXNoIjoiMHhhOWQxMjliMjRhOWY5Y2EwMWU1YTdiZGVlZGZlOTJmNDBmZmVlMGRmMjY3NjM3NGJiNGFiYWExZWQ0MmMxMGI0IiwicmV1c2VfYXZvaWRhbmNlIjp7IkJsb2NrIjowfSwiZGVhZGxpbmUiOm51bGwsImZsYXNoX2Jsb2NrIjpudWxsLCJsb2NhdGlvbiI6IkxpbWl0In0sInRvYl9yZXdhcmQiOiIweDAifV0sImFza3MiOlt7Im9yZGVyIjp7IktpbGxPckZpbGwiOnsiRXhhY3QiOnsicmVmX2lkIjowLCJleGFjdF9pbiI6ZmFsc2UsImFtb3VudCI6MTAwLCJtYXhfZXh0cmFfZmVlX2Fzc2V0MCI6MTAwLCJtaW5fcHJpY2UiOiIweDY0IiwidXNlX2ludGVybmFsIjpmYWxzZSwiYXNzZXRfaW4iOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEiLCJhc3NldF9vdXQiOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAiLCJyZWNpcGllbnQiOiIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJob29rX2RhdGEiOiIweCIsInZhbGlkX2Zvcl9ibG9jayI6MCwibWV0YSI6eyJpc0VjZHNhIjpmYWxzZSwiZnJvbSI6IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInNpZ25hdHVyZSI6IjB4In19fX0sInByaW9yaXR5X2RhdGEiOnsicHJpY2UiOiIweDY0Iiwidm9sdW1lIjoxMDAsImdhcyI6IjB4MCIsImdhc191bml0cyI6MH0sImludmFsaWRhdGVzIjpbXSwicG9vbF9pZCI6IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsImlzX2N1cnJlbnRseV92YWxpZCI6dHJ1ZSwiaXNfYmlkIjpmYWxzZSwiaXNfdmFsaWQiOnRydWUsInZhbGlkX2Jsb2NrIjowLCJvcmRlcl9pZCI6eyJhZGRyZXNzIjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwicG9vbF9pZCI6IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsImhhc2giOiIweGJkMWE1NDViYmJiYTQ4NjI2Mjc5ZTg5YTcxOTFhZDc5MjAzNmUyMTU1NzVmNjhkN2NkZGRlNjQ1NjFkMTRhNGMiLCJyZXVzZV9hdm9pZGFuY2UiOnsiQmxvY2siOjB9LCJkZWFkbGluZSI6bnVsbCwiZmxhc2hfYmxvY2siOm51bGwsImxvY2F0aW9uIjoiTGltaXQifSwidG9iX3Jld2FyZCI6IjB4MCJ9XX0=";

#[test]
fn build_and_ship_random_bundle() {
    let bytes = base64::prelude::BASE64_STANDARD.decode(BOOK).unwrap();
    let json = String::from_utf8(bytes.clone()).unwrap();
    println!("JSON: {}", json);
    let book: OrderBook = serde_json::from_slice(&bytes).unwrap();
    println!("Book: {:?}", book);
    // Will migrate things to here later, right now we have other tests to work
    // on

    // let proposal = ProposalBuilder::new()
    //     .for_pools(pools)
    //     .for_random_pools(3)
    //     .for_block(10)
    //     .order_count(50)
    //     .preproposal_count(5)
    //     .build();
    // let _bundle = AngstromBundle::from_proposal(&proposal, gas_details,
    // pools).unwrap(); Contr
}
